# Generated by Django 5.2 on 2025-04-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_recipe_category_fk_comment_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category_fk',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='recipes',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
