# Generated by Django 5.2 on 2025-04-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='submitted_at',
            new_name='timestamp',
        ),
    ]
